### ISSUE TITLE
hydra and hydra-update argc issue

### ISSUE THREAD

**Issue by Proph151Music** [Constellation-Labs/euclid-development-environment#3]
Yesterday there was a new version of argc released that seems to have broken the functionality of hydra and hydra-update.

Please see:
https://github.com/sigoden/argc/releases

To migrate from v0 to v1, the only thing you need to do is:

Replace eval "$(argc "$0" "$@")" with eval "$(argc --argc-eval "$0" "$@")" in your script.

Otherwise you may encounter an error message like this when running the script:

Argcfile not found, try `argc --argc-help` for help.

**Comment by IPadawans** [comment]
It was solved in the new tag [v0.2.0](https://github.com/Constellation-Labs/euclid-development-environment/releases/tag/v0.2.0)
