### ISSUE TITLE
Compatibility for docker-compose V2 - buildkit

### ISSUE THREAD

**Issue by flannoo** [Constellation-Labs/euclid-development-environment#5]
I recently updated my docker desktop version, which upgrades docker compose to v2.17.2 (latest version) according to the release notes. Since then, I wasn't able to build my images anymore (which worked previously), using the `scripts/hydra build` command.

When disabling the option to use docker-compose V2 in the settings of docker desktop (settings > general > "uncheck" Use Docker Compose V2), the build runs fine.

After further analyses, it seems related to the use of docker buildkit.
When I remove the line "export DOCKER_BUILDKIT=0" (which disables buildkit) on line 284 of the hydra script, it works fine when compose V2 setting is enabled.

Can this line be removed, so the script uses docker buildkit (which is now the default builder in compose v2 it seems) or is there a reason why the classic builder is still needed?

I'm on a Windows setup with WSL & docker desktop, I haven't tested this on other OS systems.

This is the error I see when enabling docker-compose V2 in docker desktop:
```
panic: assignment to entry in nil map

goroutine 14 [running]:
github.com/compose-spec/compose-go/types.MappingWithEquals.OverrideBy(...)
        github.com/compose-spec/compose-go@v1.13.2/types/types.go:427
github.com/docker/compose/v2/pkg/compose.(*composeService).build.func1({0x22b0c80, 0xc000167770}, {0xc00021cb20, 0x9})
        github.com/docker/compose/v2/pkg/compose/build.go:78 +0x7f4
github.com/docker/compose/v2/pkg/compose.(*graphTraversal).run.func1()
        github.com/docker/compose/v2/pkg/compose/dependencies.go:127 +0x63
golang.org/x/sync/errgroup.(*Group).Go.func1()
        golang.org/x/sync@v0.1.0/errgroup/errgroup.go:75 +0x64
created by golang.org/x/sync/errgroup.(*Group).Go
        golang.org/x/sync@v0.1.0/errgroup/errgroup.go:72 +0xa5
```

**Comment by Proph151Music** [comment]
I can add that I had issues with docker-compose in Ubuntu Desktop as well.  I had to manually install docker compose to get it to work.  After reading the report you just issued I took a look at the version of docker compose I am using that is working and sure enough it is v1.29.2.  👍

**Comment by IPadawans** [comment]
Hello,
@flannoo and @Proph151Music. First of all thanks for reporting the issue.  We just updated the fix to the `develop` branch, could you guys test it again and tell me if it's working properly?

**Comment by flannoo** [comment]
@IPadawans I pulled the code from the develop branch and can confirm this version is working for me :-)

**Comment by IPadawans** [comment]
Great, I'll close the issue then. We will generate a new official tag/release with this fix soon. Thanks for reporting the issue :)
