### ISSUE TITLE
docker compose v2 hydra code change

### ISSUE THREAD

**Issue by Proph151Music** [Constellation-Labs/euclid-development-environment#6]
It seems the new version of docker compose has also changed the syntax of the command that is used in the hydra script.
All instances of "docker-compose" need to change to "docker compose".

After I manually edited the hydra file with the new syntax the hydra build command was able to function.

I suppose the hydra file could search for both versions of the docker compose file.  But it seems the compose v1 file will be obsolete at the end of June anyways and all Docker packages will be updated with v2.  But in the meantime it may cause less confusion to implement a method for hydra to work as backwards compatible.

```scripts/hydra build



P12 files should be inserted on source/p12-files directory



Creating docker custom-network...

d09637eeaf38441d2ab14694cd9dc842c294d8c6db235362b987ddf1308090d0

Network created

Building ubuntu shared image...

scripts/hydra: line 288: docker-compose: command not found

Ubuntu image built

Building Global L0 image... (USING CACHE)

scripts/hydra: line 302: docker-compose: command not found

Global L0 image built

Building Currency L0 image... (USING CACHE)

scripts/hydra: line 346: docker-compose: command not found
...

**Comment by Proph151Music** [comment]
This test was run on the current develop branch.

**Comment by IPadawans** [comment]
This should be solved with the PR https://github.com/Constellation-Labs/euclid-development-environment/pull/10
